
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Add Successfully',
    EDIT_SUCCESS: 'Edit  Successfully',
    ERROR_NAME: 'Name length must be number from %d to %d',
    ERROR_NAME_EMPTY: 'Name must be non-empty',
    ERROR_NAME_DUPLICATED: 'Duplicated Name',

    ERROR_TITLE: 'Title length must be number from %d to %d',
    ERROR_TITLE_EMPTY: 'Title must be non-empty',
    ERROR_TITLE_DUPLICATED: 'Duplicated Title',
    ERROR_ORDERING: 'Ordering must be number from %d to %d',
    ERROR_STATUS: 'Status must be choose',
    ERROR_CATEGORY: "Category must be choose",
    ERROR_CATEGORY_INVALID: "Category is invalid",
    ERROR_SLUG: 'Invalid Slug',
    ERROR_SLUG_DUPLICATED: 'Duplicated Slug',
    ERROR_FILE_LIMIT: 'Invalid Size File',
    ERROR_FILE_EXTENSION: 'Invalid Type File',
    ERROR_FILE_EMPTY: 'Must upload photo',
    ERROR_DESCRIPTION: 'Description must be non-empty',
    ERROR_SOURCE: 'Source must be non-empty',
    ERROR_SETTING_TITLEPAGE: 'Please input Title Page',
    ERROR_SETTING_ADDRESS: 'Please input Address',
    ERROR_SETTING_PHONENUMBER: 'Please input Phone Number',
    ERROR_SETTING_EMAIL: 'Please input Email',
    ERROR_SETTING_COPPYRIGHT: 'Please input Coppyright',
    ERROR_SETTING_URLFACEBOOK: 'Input link Facebook wrong',
    ERROR_SETTING_URLTWITTER:'Input link Twitter wrong',
    RROR_SETTING_URLINSTAGRAM:'Input link Instagram wrong',
    ERROR_SETTING_URLYOUTUBE:'Input link Youtube wrong',
    ERROR_SETTING_URLLINKEDIN:'Input link LinkedIN wrong',
    ERROR_RSS_URL:"Input link wrong",
    ERROR_SUBJECT: 'Subject must be non-empty',
    ERROR_API_EMPTY: 'API must be non-empty',
    ERROR_EMAIL: "Please input Email",
    ERROR_MESSAGE: "Please input Message",
    SUCCESS_SETTING_SAVE: 'Save Setting Successfully',
    ERROR_NOT_EXITS: 'Not Exits'
};